default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_products_development

test:
  <<: *default
  database: food_products_test

production:
  <<: *default
  database: food_products_production
  username: food_products
  password: <%= ENV['FOOD_PRODUCTS_DATABASE_PASSWORD'] %>
